apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc
  namespace: frpc
data:
  frpc.ini: |-
    [common]
    server_addr = deltavoid.cloud
    server_port = 7000
    log_level=info


    [argocd_10082]
    type = tcp
    local_ip=argocd-server.argocd
    local_port=80
    remote_port=10082

    [hello_nginx_10083]
    type = tcp
    local_ip=hello-nginx.hello-nginx
    local_port=80
    remote_port=10083

    [hello_nginx_10084]
    type = tcp
    local_ip=hello-nginx-proxy.hello-nginx
    local_port=80
    remote_port=10084

    [wordpress_10085]
    type = tcp
    local_ip=my-wordpress.wordpress
    local_port=80
    remote_port=10085
