apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: basic-daemonset
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/deltavoid/k8s_cluster_101.git
    targetRevision: HEAD
    path: basic-daemonset

  destination:
    server: https://kubernetes.default.svc
    namespace: basic-daemonset

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

